version: "3.8"
services:
    mysql:
      container_name: mysql
      image: mysql:8.0.32
      restart: always
      volumes:
        - db_data:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=db
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
      ports:
        - 3307:3306

    api:
      build: ./
      depends_on:
        - mysql
      environment:
        - DB_NAME=db
        - DB_HOST=mysql
        - DB_PORT=3306
        - DB_USER=user
        - DB_PASSWORD=password
      ports:
        - 8080:8080
volumes:
  db_data:
